"""Golden set: a curated, VERIFIED sample of the spec-first geometry->TikZ dataset.

Every row is generated by the same seeded engine as the full dataset (v2
coordinate-free CONSTRUCTION target: the model emits the construction, PGF
computes the numbers), then run through the project's own falsifiable gate:

    figure-only  AND  compiles under tectonic  AND  every named point within
    0.05 of the ground-truth construction.

Only rows that pass are kept, so the set is correct-by-construction *and*
independently verified by the same grader used to score models. It is balanced
across operations (foot-of-altitude, line-intersection, reflection, midpoint,
point-on-circle), chain lengths (2-5), and round vs irregular numbers, and it is
disjoint from the held-out eval sets.

Usage:
  uv run python scripts/build_golden_set.py                    # 150 -> data/golden_set.jsonl
  uv run python scripts/build_golden_set.py --workers 10
"""

from __future__ import annotations

import argparse
import json
import random
import sys
from collections import Counter
from concurrent.futures import ThreadPoolExecutor
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parents[1] / "src"))

from geotikz import metrics, tex  # noqa: E402
from geotikz.generator import make_example  # noqa: E402
from geotikz.prompts import to_chat_example  # noqa: E402

ROOT = Path(__file__).resolve().parents[1]

# (chain, irregular, force_op, easy_only, count). Weighted toward the hard ops
# the frontier sweep found unreliable (foot-of-altitude, line-intersection),
# with an easy/round/short tail so the set shows the whole behavior, not just the
# failure region.
GOLDEN_MIX: list[tuple[int, bool, str | None, bool, int]] = [
    (4, True,  "foot_altitude", False, 25),   # the star: hard op, irregular
    (5, True,  "foot_altitude", False, 15),
    (4, False, "foot_altitude", False, 10),   # same hard op, round numbers
    (3, True,  "intersection",  False, 15),   # secondary hard op
    (4, True,  "intersection",  False, 15),
    (4, True,  None,            False, 20),   # natural mix, irregular
    (5, True,  None,            False, 10),
    (2, True,  None,            False, 10),   # short + irregular
    (3, False, None,            False, 10),   # mixed, round
    (3, True,  None,            True,  10),   # easy-only control, irregular
    (2, False, None,            True,  10),   # simplest: easy-only, round
]


def verify(ex: dict, atol: float = 0.05) -> bool:
    """Run the ground-truth figure through the project's own PASS gate."""
    tikz = ex["tikz"]
    if not metrics.is_figure_only(tikz):
        return False
    cr = tex.compile_tikz(tikz)
    try:
        if not cr.ok:
            return False
    finally:
        cr.cleanup()  # never leak the compile tempdir
    return bool(metrics.coord_match(tikz, ex["points"], atol=atol)["all_correct"])


def load_blocklist(paths: list[str]) -> set[str]:
    block: set[str] = set()
    for p in paths:
        fp = ROOT / p
        if fp.exists():
            for line in fp.read_text().splitlines():
                if line.strip():
                    block.add(json.loads(line)["description"])
    return block


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument("--seed", type=int, default=2026)
    ap.add_argument("--workers", type=int, default=10)
    ap.add_argument("--oversample", type=int, default=3, help="candidates per wanted row")
    ap.add_argument("--out", type=str, default="data/golden_set.jsonl")
    args = ap.parse_args()

    if not tex.has_tectonic():
        sys.exit("tectonic not found — it's required to verify that every row compiles.")

    rng = random.Random(args.seed)
    block = load_blocklist(["data/eval.jsonl", "data/eval_pgf.jsonl"])
    print(f"blocklist (held-out eval scenes, kept disjoint): {len(block)}")
    seen: set[str] = set()

    # 1) generate candidate pools per cell (cheap, pure python)
    cells: list[tuple[int, int, list[dict]]] = []
    for ci, (chain, irr, op, easy, count) in enumerate(GOLDEN_MIX):
        pool: list[dict] = []
        need = count * args.oversample
        tries, cap = 0, need * 400 + 5000
        while len(pool) < need and tries < cap:
            tries += 1
            ex = make_example(rng, chain, irr, force_op=op, easy_only=easy, symbolic=True)
            if ex["chain"] != chain or (op and op not in ex["tags"]):
                continue
            d = ex["description"]
            if d in block or d in seen:
                continue
            seen.add(d)
            ex["_cell"] = ci
            pool.append(ex)
        cells.append((ci, count, pool))

    # 2) verify every candidate in parallel (compile is the slow part)
    cand = [ex for _, _, pool in cells for ex in pool]
    print(f"verifying {len(cand)} candidates on {args.workers} workers (compile + coord gate)...")
    with ThreadPoolExecutor(max_workers=args.workers) as pool_exec:
        oks = list(pool_exec.map(verify, cand))
    for ex, ok in zip(cand, oks):
        ex["_ok"] = ok

    # 3) keep the first `count` verified rows per cell
    chosen: list[dict] = []
    for ci, count, pool in cells:
        good = [ex for ex in pool if ex["_ok"]][:count]
        if len(good) < count:
            chain, irr, op, easy, _ = GOLDEN_MIX[ci]
            tag = op or ("easy" if easy else "mixed")
            print(f"  WARN cell {ci} (c{chain} {'irr' if irr else 'rnd'} {tag}): "
                  f"only {len(good)}/{count} verified")
        chosen += good
    rng.shuffle(chosen)

    # 4) write jsonl (raw, for grading) + chat jsonl (system/user/assistant, for SFT)
    out = ROOT / args.out
    out.parent.mkdir(parents=True, exist_ok=True)
    clean = [{**{k: v for k, v in ex.items() if not k.startswith("_")}, "id": i}
             for i, ex in enumerate(chosen)]
    with out.open("w") as f:
        for row in clean:
            f.write(json.dumps(row) + "\n")
    chat = out.with_name(out.stem + "_chat.jsonl")
    with chat.open("w") as f:
        for row in clean:
            f.write(json.dumps(to_chat_example(row)) + "\n")

    # 5) composition report
    ops = Counter(t for r in clean for t in r["tags"])
    chains = Counter(r["chain"] for r in clean)
    irr = sum(r["irregular"] for r in clean)
    print(f"\nwrote {len(clean)} rows -> {out}  (+ {chat.name})")
    print(f"candidate verified rate: {sum(oks)}/{len(oks)} = {sum(oks) / (len(oks) or 1):.3f}")
    print(f"chain lengths: {dict(sorted(chains.items()))}")
    print(f"numbers: irregular {irr}/{len(clean)}, round {len(clean) - irr}/{len(clean)}")
    print(f"operation tags: {dict(ops.most_common())}")


if __name__ == "__main__":
    main()
